version: '3.6'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
     - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      USER_ID: 1000 # adjust in case of permission problems with mounted volumes
    volumes:
      - .wordpress/plugins:/var/www/html/wp-content/plugins
      - .wordpress/themes:/var/www/html/wp-content/themes
      - .wordpress/uploads:/var/www/html/wp-content/uploads
      - ./vits_coffee_finder:/var/www/html/wp-content/plugins/vits_coffee_finder
      - ./show-single-variations-premium:/var/www/html/wp-content/plugins/show-single-variations-premium
      - ./vits_coffee_finder_landing_page.php:/root/vits_coffee_finder_landing_page.php
      - ./bootstrap-wp.sh:/root/bootstrap-wp.sh




volumes:
  data_db: 